<a href="https://colab.research.google.com/github/gachet/ad-1-24/blob/main/LOG/Untitled17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [76]:
data = pd.read_csv("https://drive.google.com/uc?id=15ZhrQgD8Gi7a-OI9GoDeNTnR5aJOJ1xB")
data

0.051267   0.69956  1
0   -0.092742  0.684940  1
1   -0.213710  0.692250  1
2   -0.375000  0.502190  1
3   -0.513250  0.465640  1
4   -0.524770  0.209800  1
..        ...       ... ..
112 -0.720620  0.538740  0
113 -0.593890  0.494880  0
114 -0.484450  0.999270  0
115 -0.006336  0.999270  0
116  0.632650 -0.030612  0

[117 rows x 3 columns]

In [89]:
data = np.array(data)
X = data[:, [0,1]] *100
y = data[:, [2]]

In [90]:
X.shape[1]

2

In [91]:
X = np.insert(X, 0, values=1, axis=1)
theta = np.zeros((X.shape[1],1))


In [80]:
X[0:5,:]

array([[  1.    ,  -9.2742,  68.494 ],
       [  1.    , -21.371 ,  69.225 ],
       [  1.    , -37.5   ,  50.219 ],
       [  1.    , -51.325 ,  46.564 ],
       [  1.    , -52.477 ,  20.98  ]])

In [81]:
y[0:5,:]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [92]:
theta

array([[0.],
       [0.],
       [0.]])

In [84]:
def sigmoid(z):
 return 1 / (1 + np.exp(-z))

In [93]:
def loss(theta, X, y):
    m = len(y)
    h= sigmoid(X.dot(theta))
    J = (1.0/m)* -np.sum(y * np.log(h) + (1 - y) * np.log(1 - h))
    return J

In [100]:
def gradient_descent(theta, X, y, alpha, num_iterations):
    for i in range(num_iterations):
        h = sigmoid(X.dot(theta))
        gradient = X.T.dot(y - h)
        #gradients = np.dot(errors.T, X).T
        theta -= alpha * gradient
    return theta

In [101]:
theta = gradient_descent(theta, X, y, alpha=0.0001, num_iterations=10000)

<ipython-input-84-30324c947e76>:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


In [97]:
theta

array([[   -52.63700694],
       [ 26254.69517378],
       [-17836.41902559]])

In [36]:
def predict(theta, X):
    h = sigmoid(X.dot(theta))
    y_pred = np.where(h >= 0.5, 1, 0)
    return y_pred



In [37]:
y_pred = predict(theta, X)
y_pred

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [ ]:
accuracy = np.mean(y_pred == y)
print("Accuracy:", accuracy)