<a href="https://colab.research.google.com/github/gachet/ad-1-24/blob/main/pca/para_nuria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


x = [19,39,30,30,15,15,15,30]
y= [63,74,87,23,35,43,32,73]
originales =np.stack ((x, y), axis=1)
mean_col = np.mean(originales, axis=0)
data1 = originales - mean_col


#Ejemplo de las traspas de clase

In [ ]:
originales

array([[19, 63],
       [39, 74],
       [30, 87],
       [30, 23],
       [15, 35],
       [15, 43],
       [15, 32],
       [30, 73]])

#Datos normalizados con la medoa

In [ ]:
data1

array([[ -5.125,   9.25 ],
       [ 14.875,  20.25 ],
       [  5.875,  33.25 ],
       [  5.875, -30.75 ],
       [ -9.125, -18.75 ],
       [ -9.125, -10.75 ],
       [ -9.125, -21.75 ],
       [  5.875,  19.25 ]])

#Covarianza

In [ ]:
A=np.cov(data1.T)
A

array([[ 85.83928571, 121.32142857],
       [121.32142857, 551.07142857]])

#Autovalores y autovectores

In [ ]:
autovalor, autovector = np.linalg.eig(A )
autovalor

array([ 56.10230167, 580.80841262])

In [ ]:
autovector

array([[-0.97124992, -0.23806218],
       [ 0.23806218, -0.97124992]])

#Tomamos el autovector 2 , el que se relaciona con el autovalor mas grande, sería la CP1

In [ ]:
autovector1=autovector[1,0:2]
autovector1.reshape(2,-1)

array([[ 0.23806218],
       [-0.97124992]])

In [ ]:
data_reduced = np.dot(data1, autovector1.T)
data_reduced

array([-10.20413038, -16.12663594, -30.89544444,  31.26455022,
        16.03861858,   8.26861925,  18.95236833, -17.29794561])

In [ ]:
data_reduced.shape

(8,)

In [ ]:
data_reduced= data_reduced.reshape(,8)

In [ ]:
data_reduced.shape

(1, 8)

In [ ]:
data_reduced

array([[-10.20413038, -16.12663594, -30.89544444,  31.26455022,
         16.03861858,   8.26861925,  18.95236833, -17.29794561]])

In [ ]:
autovector1 = autovector1.reshape(1, -1)

In [ ]:
autovector1

array([[ 0.23806218, -0.97124992]])

In [ ]:
autovector1.shape

(2,)

In [ ]:
data_original = np.dot(autovector1,data_reduced) +mean_col
data_original

ValueError: shapes (2,) and (1,8) not aligned: 2 (dim 0) != 1 (dim 0)

In [ ]:
originales

array([[19, 63],
       [39, 74],
       [30, 87],
       [30, 23],
       [15, 35],
       [15, 43],
       [15, 32],
       [30, 73]])

In [ ]:
data_reduced2 = np.dot(data1, autovector.T)
data_reduced2

array([[  2.77558069, -10.20413038],
       [-19.26810157, -16.12663594],
       [-13.62166061, -30.89544444],
       [  1.61431865,  31.26455022],
       [ 13.32632129,  16.03861858],
       [ 11.42182388,   8.26861925],
       [ 14.04050782,  18.95236833],
       [-10.28879015, -17.29794561]])

In [ ]:
data_original2 = np.dot(data_reduced2, autovector) +mean_col
data_original2

array([[19., 63.],
       [39., 74.],
       [30., 87.],
       [30., 23.],
       [15., 35.],
       [15., 43.],
       [15., 32.],
       [30., 73.]])