<a href="https://colab.research.google.com/github/gachet/ad-1-24/blob/main/pca/para_nuria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.decomposition import PCA
import seaborn as sns; sns.set()

x = [19,39,30,30,15,15,15,30]
y= [63,74,87,23,35,43,32,73]
originales =np.stack ((x, y), axis=1)
mean_col = np.mean(originales, axis=0)
data1 = originales - mean_col


In [108]:
data1

array([[ -5.125,   9.25 ],
       [ 14.875,  20.25 ],
       [  5.875,  33.25 ],
       [  5.875, -30.75 ],
       [ -9.125, -18.75 ],
       [ -9.125, -10.75 ],
       [ -9.125, -21.75 ],
       [  5.875,  19.25 ]])

In [109]:
A=np.cov(data1.T)
A

array([[ 85.83928571, 121.32142857],
       [121.32142857, 551.07142857]])

In [110]:
autovalor, autovector = np.linalg.eig(A )
autovalor

array([ 56.10230167, 580.80841262])

In [111]:
autovector

array([[-0.97124992, -0.23806218],
       [ 0.23806218, -0.97124992]])

In [112]:
autovector1=autovector[1,0:2]
autovector1.reshape(1,-1)

array([[ 0.23806218, -0.97124992]])

In [113]:
autovector1.shape

(2,)

In [114]:
data_reduced = np.dot(data1, autovector[1].T)
data_reduced

array([-10.20413038, -16.12663594, -30.89544444,  31.26455022,
        16.03861858,   8.26861925,  18.95236833, -17.29794561])

In [115]:
data_reduced.shape

(8,)

In [116]:
data_reduced= data_reduced.reshape(8,-1)

In [117]:
data_reduced.shape

(8, 1)

In [118]:
data_reduced

array([[-10.20413038],
       [-16.12663594],
       [-30.89544444],
       [ 31.26455022],
       [ 16.03861858],
       [  8.26861925],
       [ 18.95236833],
       [-17.29794561]])

In [119]:
autovector1 = autovector1.reshape(1, -1)

In [120]:
autovector1

array([[ 0.23806218, -0.97124992]])

In [121]:
autovector1.shape

(1, 2)

In [122]:
data_original = np.dot(data_reduced, autovector1) +mean_col
data_original

array([[21.69578252, 63.66076078],
       [20.28585796, 69.41299381],
       [16.76996327, 83.75719784],
       [31.56790685, 23.38430821],
       [27.94318844, 38.17249304],
       [26.09344549, 45.71910425],
       [28.63684204, 35.34251384],
       [20.00701343, 70.55062823]])

In [123]:
originales

array([[19, 63],
       [39, 74],
       [30, 87],
       [30, 23],
       [15, 35],
       [15, 43],
       [15, 32],
       [30, 73]])

In [128]:
data_reduced2 = np.dot(data1, autovector.T)
data_reduced2

array([[  2.77558069, -10.20413038],
       [-19.26810157, -16.12663594],
       [-13.62166061, -30.89544444],
       [  1.61431865,  31.26455022],
       [ 13.32632129,  16.03861858],
       [ 11.42182388,   8.26861925],
       [ 14.04050782,  18.95236833],
       [-10.28879015, -17.29794561]])

In [129]:
data_original2 = np.dot(data_reduced2, autovector) +mean_col
data_original2

array([[19., 63.],
       [39., 74.],
       [30., 87.],
       [30., 23.],
       [15., 35.],
       [15., 43.],
       [15., 32.],
       [30., 73.]])