<a href="https://colab.research.google.com/github/gachet/ad-1-24/blob/main/algo/ejer_Multivariable_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Ejercicio Regresión Lineal Multivariable



#### Librerías

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.axes3d import Axes3D
%matplotlib inline

#### Datos
El siguiente conjunto de datos contiene la tensión arterial sistólica (mmHg) (variable dependiente a predecir), la edad (años) y el peso (libras, 1 libra = 0.39 Kg) (mmHg) (variables independientes o predictoras)


In [ ]:
# X1 = systolic blood pressure; X2 = age in years, X3 = weight in pounds
blood_pressure_data = np.array([
    [132, 52, 173],
    [143, 59, 184],
    [153, 67, 194],
    [162, 73, 211],
    [154, 64, 196],
    [168, 74, 220],
    [137, 54, 188],
    [149, 61, 188],
    [159, 65, 207],
    [128, 46, 167],
    [166, 72, 217]
])


X: 

[[  1.  52. 173.]
 [  1.  59. 184.]
 [  1.  67. 194.]
 [  1.  73. 211.]
 [  1.  64. 196.]
 [  1.  74. 220.]
 [  1.  54. 188.]
 [  1.  61. 188.]
 [  1.  65. 207.]
 [  1.  46. 167.]
 [  1.  72. 217.]]
